version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/node:15.0.1-browsers
        environment: 
          CHROME_BIN: "/usr/bin/google-chrome"

    # working_directory: ~/repo

    steps:
      - run:
            name: "Checking Versions"
            command: |
              node --version
              npm --version
              
      - checkout

      # install dependencies
      - run: npm i

      # run tests!
      - run: npm test
